name: flickerflow
services:
  video-service:
    image: feliperomero/flickerflow-video:latest
    build:
      context: ./video-service
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=development
      - DEBUG=video-service:*
      - VIDEO_STORAGE_HOST=storage-service
      - VIDEO_STORAGE_PORT=4001
    restart: "no"
  storage-service:
    image: feliperomero/flickerflow-storage:latest
    build:
      context: ./storage-service
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    environment:
      - PORT=4001
      - NODE_ENV=development
      - DEBUG=storage-service:*
      - STORAGE_CONTAINER_NAME=videos
      - STORAGE_HOST=azurite
      - STORAGE_PORT=10000
      - STORAGE_ACCOUNT_NAME=devstoreaccount1
      - STORAGE_ACCOUNT_KEY=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==
    restart: "no"
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    restart: "no"
