version: '3'
services:
  flickerflow:
    image: feliperomero/flickerflow
    build:
      context: ./flicker-flow
      dockerfile: Dockerfile
    container_name: flickerflow
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - NODE_ENV=development
      - DEBUG=flicker-flow:*
    restart: "no"
